//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

#[cfg(feature = "ssr")]
pub mod prelude;

pub mod enums;

pub mod change_list;

pub mod user;

/// Client shouldn't have any visibility of oauth tokens at all.
#[cfg(feature = "ssr")]
pub mod oauth_token;
