use serde::{Deserialize, Serialize};

/// User entity.
///
/// # Fields
///
/// * `id`: The unique identifier for the user. This is automatically
///   generated by the database.
/// * `username`: The user's username. This field is optional and must
///   be unique if provided.
/// * `email`: The user's email address. This field is optional and must
///    be unique if provided.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Model {
    /// The timestamp when the change list item was created.
    pub username: String,
    /// The timestamp when the change list item was last updated.
    pub email: String,
}
