#![allow(clippy::doc_markdown)]
#![allow(clippy::used_underscore_items)]

use cfg_if::cfg_if;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

cfg_if! { if #[cfg(feature = "ssr")]{

    use sea_orm::entity::prelude::*;

    /// User entity.
    ///
    /// # Fields
    ///
    /// * `id`: The unique identifier for the user.  This is automatically
    ///   generated by the database.
    /// * `username`: The user's username. This field is optional and must
    ///   be unique if provided.
    /// * `email`: The user's email address. This field is optional and must
    ///    be unique if provided.
    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, DeriveEntityModel)]
    #[sea_orm(table_name = "user")]
    pub struct Model {
        #[sea_orm(primary_key, auto_increment = false)]
        /// The unique identifier for the change list item.
        pub id: Uuid,
        /// The timestamp when the change list item was created.
        pub username: String,
        /// The timestamp when the change list item was last updated.
        pub email: String,
    }

    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
    pub enum Relation {}

    impl ActiveModelBehavior for ActiveModel {}

}}
